FROM rayproject/ray:latest-py312-cpu as base

USER root

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN wget --quiet https://deb.nodesource.com/setup_lts.x && \
    bash setup_lts.x && \
    rm -fv setup_lts.x && \
    apt-get update

RUN apt-get install -y procps iputils-ping nodejs build-essential

RUN apt-get clean

FROM base as ray

USER ray

RUN mkdir -p /home/ray/aworld

WORKDIR /home/ray/aworld

COPY ./aworld aworld
COPY ./mcp_servers mcp_servers
COPY ./setup.py setup.py

RUN pip install -e .

RUN pip install -r ./mcp_servers/requirements.txt 

FROM ray

COPY ./examples/ examples

RUN pip install -r ./examples/web/agent_deploy/ray_agent/requirements.txt

# Fix numpy ray compatibility issues
RUN pip install -U "numpy>=1.19,<2.0" "pyarrow>=14.0.2" "grpcio==1.66.2"

ENV RAY_memory_monitor_refresh_ms=0
ENV RAY_object_store_memory=1000000000
ENV RAY_memory_usage_threshold=0.9